### ISSUE TITLE
[getting started guide] broken links to missing services.md

### ISSUE THREAD

**Issue by honstar** [adobe/helix-home#168] opened 2020-11-22 10:25 UTC
While going through the [getting started guide](https://github.com/adobe/helix-home/blob/main/getting-started.md), I stumbled over 2 broken links in the _Deploy your Helix Site_ section:
- access to adobe i/o runtime
- access to fastly

Both of the above link `services.md` of the project-helix repository that doesn't exist anymore.

Getting access to i/o runtime could link directly to https://www.adobe.io/apis/experienceplatform/runtime/docs.html#!adobedocs/adobeio-runtime/master/overview/getting_access.md.

**Comment by rofe** [comment] 2020-11-22 12:12
Cannot reproduce: the getting started guide links to `SERVICES.md` which exists since 2018. Could it be you don't have (or lost) access to the `project-helix` repo? You need to be a member of the adobe GH org.

Also, the doc you mentioned is geared towards external parties, and to be honest I'm not sure we want to encourage people outside Adobe to use anything other than Helix Pages at this point. Keeping these 2 links Adobe-internal for now is intentional.

**Comment by rofe** [comment] 2020-12-10 14:06
Closing

**Closed by rofe** 2020-12-10 14:06 UTC
Labels: docmeplz
